# Generated by Django 4.0.6 on 2022-10-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0005_alter_cashbook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbook',
            name='user',
        ),
    ]
